spring:
  application:
    name: cardefectscan
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_by.default_null_ordering: last
        format_sql: true
        default_schema: public
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/cardefectscan
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  mustache:
    check-template-location: false

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /


auth:
  refresh-lifespan: 604800
  jwt:
    lifespan: 6000
    private-key: FJBXvKdzYl0ZlIxC6oTO2HTnitxjdxXX9v5gLG4hYRIbSY3YBtVmWYMRHYmYTguB
  cookies:
    is-http-only: false
    max-age: 604800
    is-secure: false
    domain: localhost

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  put-link-expiration: 6000
  get-link-expiration: 6000

client:
  model-service-host: http://localhost:8888

app:
  host: http://localhost:8080